name: nih-ad
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - pip=20.3
  - cudatoolkit=11.3
  - pip:
      - torch==2.0.1
      - torchvision>=0.15.2
      - albumentations==1.3.0
      - opencv-contrib-python
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.9
      - pytorch-lightning
      - omegaconf==2.3.0
      - test-tube>=0.7.5
      - streamlit==1.12.1
      - einops==0.6.1
      - transformers
      - webdataset==0.2.5
      - kornia==0.6.9
      - open_clip_torch>=2.20.0
      - invisible-watermark>=0.2.0
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==1.0.1
      - timm>=0.6.13
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors>=0.2.7
      - basicsr==1.4.2
      - fvcore
      - pycocotools
      - wandb>=0.15.6
      - tqdm==4.65.0
      - moviepy
      - av==10.0.0
      - xformers==0.0.20
      - numpy==1.24.4
      - audiocraft==1.0.0
      - flashy>=0.0.1
      - hydra-core>=1.1
      - hydra_colorlog
      - julius
      - num2words
      - sentencepiece
      - spacy
      - torchaudio>=2.0.2
      - huggingface_hub
      - demucs
      - librosa
      - encodec
      - protobuf
      - ffmpeg==1.4
      - gradio
      - uuid
      - accelerate>=0.20.3
      - black==23.7.0
      - chardet==5.1.0
      - clip @ git+https://github.com/openai/CLIP.git
      - fairscale>=0.4.13
      - fire>=0.5.0
      - fsspec>=2023.6.0
      - matplotlib>=3.7.2
      - natsort>=8.4.0
      - ninja>=1.11.1
      - pandas>=2.0.1
      - pillow>=9.5.0
      - pudb>=2022.1.3
      - pyyaml>=6.0.1
      - scipy>=1.10.1
      - tensorboardx==2.6
      - tokenizers==0.12.1
      - torchdata==0.6.1
      - triton==2.0.0
      - urllib3<1.27,>=1.25.4
      - wheel>=0.41.0
      - decord==0.6.0
      - diffusers[torch]==0.21.0
      - rotary_embedding_torch
      - open-clip-torch>=2.20.0
      - git+https://github.com/suno-ai/bark.git
      - requests
      - rich
      - scikit-learn
      - plyfile
      - pygltflib
      - dearpygui
      - xatlas
      - trimesh
      - PyMCubes
      - pymeshlab
      - rembg[gpu,cli]
      - -e git+https://github.com/NVlabs/nvdiffrast.git@main#egg=nvdiffrast
      - -e git+https://github.com/ashawkey/kiuikit.git@main#egg=kiui
      - -e ./dreamgaussian/simple-knn
      - -e ./dreamgaussian/diff-gaussian-rasterization