name: nih-ad
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip=20.3
  - cudatoolkit=11.3
  - pip:
      - torch==2.0.0
      - torchvision
      #- gradio==3.16.2
      - albumentations==1.3.0
      - opencv-contrib-python
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.8.3
      - omegaconf==2.1.1
      - test-tube>=0.7.5
      - streamlit==1.12.1
      - einops==0.3.0
      - transformers==4.31.0
      - webdataset==0.2.5
      - kornia==0.6
      - open_clip_torch==2.0.2
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==0.7.0
      - timm==0.6.12
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors>=0.2.7
      - basicsr==1.4.2
      - fvcore
      - pycocotools
      - wandb
      - tqdm==4.65.0
      - moviepy
      - av
      - xformers
      - numpy==1.24.2
      - audiocraft==1.0.0
      - flashy>=0.0.1
      - hydra-core>=1.1
      - hydra_colorlog
      - julius
      - num2words
      - sentencepiece
      - spacy
      - torchaudio>=2.0.0
      - huggingface_hub
      - demucs
      - librosa
      - encodec
      - protobuf
      - ffmpeg
      - https://gradio-builds.s3.amazonaws.com/756e3431d65172df986a7e335dce8136206a293a/gradio-4.7.1-py3-none-any.whl
      - diffusers
      - uuid
      - accelerate